### ISSUE TITLE
Key exchange document discrepancy

### ISSUE THREAD

**Issue by leonmf** [metafetish/buttshock-protocol-docs#12]
In the et312-protocol.org key exchange section, it indicates the following:

*** Key Exchange

After the handshake ends, you can then send "Read Byte" commands
without performing a key exchange.  If you wish to "Write Bytes"
then XOR keys must be exchanged. This involves
sending a 3 byte sequence to the box, and receiving 3 bytes back:

- [0x2f, 0xVV, 0xWW] sent to ET312
- [0x21, 0xXX, 0xYY] is read from ET312

However, manual.doc shows that the nibbles in the host code should be swapped for xor on page 3.

This may not affect most people since a host code of 0x00 will be used causing the byte order to be unimportant for, literally everybody, and I'm just picking nits.

**Comment by leonmf** [comment]
It should be noted that I haven't actually tested anything with my box yet as I'm waiting parts so this just comes out of my obsessive combing through documents...

**Comment by qdot** [comment]
Great catch! I'll get that fixed. Need to put comments about it in the code too, as someone had mentioned trying to use a non-zero key and was wondering why it didn't work.
