### ISSUE TITLE
Document 2b cable building

### ISSUE THREAD

**Issue by qdot** [metafetish/buttshock-protocol-docs#8]
Need to figure out pinouts on 2b cable. Hopefully similar to Erostek cable.

**Comment by kinkyhacks** [comment]
http://shop.clickandbuild.com/cnb/shop/ftdichip?productID=69&op=catalogue-product_info-null&prodCategoryID=103

**Comment by qdot** [comment]
Issue moved to [metafetish/stpihkal #27](https://github.com/metafetish/stpihkal/issues/27) via [**ZenHub**](https://www.zenhub.com/)
